### ISSUE TITLE
why not just use the w2v_256d that is provided by ZHIHU?  

### ISSUE THREAD

**Issue by coderSkyChen** [brightmart/text_classification#10]
Do you have any experiments that compare w2v_256（ZHIHU provide） with w2v_100（trained by yourself）？

**Comment by brightmart** [comment]
i did not do experiment to compare the provided one with mine.

i also have my own w2v_256, and w2v_512. it took longer or more resource to train these compare to w2v_100, and prone to overfit in some of my model.

how about you, what did you find, and how did you use the provieded one.
