### ISSUE TITLE
The input_y of  (p8_TextRNN_train.py)

### ISSUE THREAD

**Issue by Amanda-1997** [brightmart/text_classification#101]
When training p8_TextRNN_train.py，is there anyone meeting the follow problem?

Sometimes it can work as a normal one, Sometimes it doesn't work as follows……

![image](https://user-images.githubusercontent.com/28642602/50208165-704e9580-03ab-11e9-9aff-a78018245275.png)

**Comment by brightmart** [comment]
it seems it works.
