### ISSUE TITLE
could you give a brief intro about the ensemble

### ISSUE THREAD

**Issue by realfaker** [brightmart/text_classification#11]
Hi bright,

nice job on these baselines. I saw you said you did some ensemble work, so could you give some words about?

I didn't find a good way to do a traditional bagging or boosting, and I tried the [hard voting](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.VotingClassifier.html), but results' bad. :-(

**Comment by brightmart** [comment]
you can read paper: 'Ensemble Selection from Libraries of Models'. you can try basic method from this paper. the result is fine for me.
