### ISSUE TITLE
where is the _word_voabulary.pik file

### ISSUE THREAD

**Issue by hqd2009** [brightmart/text_classification#12]
when I run a01_FastText/p5_fastTextB_train.py, but I get a error "can not find p4_zhihu_load_data library".

Then, I modify the code as 
"
sys.path.append('../aa1_data_util')
from data_util_zhihu import load_data,create_voabulary,create_voabulary_label
"

but I get:

cache_path: cache_vocabulary_label_pik/_word_voabulary.pik file_exists: False
create vocabulary. word2vec_model_path: zhihu-word2vec-title-desc.bin-100
Traceback (most recent call last):
  File "p5_fastTextB_train.py", line 159, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "p5_fastTextB_train.py", line 42, in main
    vocabulary_word2index, vocabulary_index2word = create_voabulary()
  File "../aa1_data_util/data_util_zhihu.py", line 40, in create_voabulary
    with open(cache_path, 'a') as data_f:
FileNotFoundError: [Errno 2] No such file or directory: 'cache_vocabulary_label_pik/_word_voabulary.pik'

So where is the _word_voabulary.pik file? how can I get it?

**Comment by brightmart** [comment]
xxx.pik is just a cached file. once you generated it, it will save in file system, so next time you can use it directly.
even you don't have this file it is o.k. just change the code to let the function to generate index-vocabulary pair each time.
for more detail, you can check:
files in a08_EntityNetwork, which is more recently.

**Comment by hqd2009** [comment]
@brightmart 
thank you! I fix this bug, but when I run a08_EntityNetwork/a03_train.py, I get a new bug:
FileNotFoundError: [Errno 2] No such file or directory: 'train-zhihu4-only-title-all.txt'

How can I find this txt file?

**Comment by brightmart** [comment]
please find it in: https://pan.baidu.com/s/1jI7R4X4
