### ISSUE TITLE
import word2vec

### ISSUE THREAD

**Issue by mudeguo** [brightmart/text_classification#13]
i tried to run the sample. but i found the code" import word2vec" in data_util_zhihu.py couldn't work. i want to know where can i download the word2vec, thank you very mcuh.

**Comment by brightmart** [comment]
quote from a reader:
I solved it!And find it to be 'from gensim.models.Word2vec import word2vec' in my version

**Comment by mudeguo** [comment]
> from gensim.models.word2vec import word2vec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'word2vec'

it still doesnot work!

**Comment by mudeguo** [comment]
'from gensim.models  import word2vec' , it works. thank you.
