### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by lydemo** [brightmart/text_classification#16]
I try to run p7_TextCNN_train.py in a02_TextCNN, and I've downloaded the zhihu-word2vec-title-desc.bin-100 and put it in the same place as p7_TextCNN_train.py, then the error occurs: [Errno 2] No such file or directory: 'cache_vocabulary_label_pik/cnn2_word_voabulary.pik'
I've noticed that someone met almost the same problem as me, but I don't understand now that cnn2_word_voabulary.pik does not exist, how can the program utilize it? I can't figure out how to debug it. Should I update somewhere in the program?

**Comment by brightmart** [comment]
1. first you should create a folder name: "cache_vocabulary_label_pik".
2. cnn2_word_voabulary.pik will be created under a function create_voabulary at data_util_zhihu.py. you can see from the code that it will be created if it is not exist; otherwise, it will be used.

**Comment by lydemo** [comment]
Then another error occurs:
Traceback (most recent call last):
  File "E:/test/text_classification-master/text_classification-master/a02_TextCNN/p7_TextCNN_train.py", line 197, in <module>
    tf.app.run()
  File "E:\Anaconda\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "E:/test/text_classification-master/text_classification-master/a02_TextCNN/p7_TextCNN_train.py", line 48, in main
    vocabulary_word2index, vocabulary_index2word = create_voabulary(word2vec_model_path=FLAGS.word2vec_model_path,name_scope="cnn2") #simple='simple'
  File "E:\test\text_classification-master\text_classification-master\aa1_data_util\data_util_zhihu.py", line 18, in create_voabulary
    vocabulary_word2index, vocabulary_index2word=pickle.load(data_f)
TypeError: a bytes-like object is required, not 'str'
cache_path: cache_vocabulary_label_pik/cnn2_word_voabulary.pik file_exists: True

I know it's caused by pickle, but how to fix the error?

**Comment by brightmart** [comment]
you may  paas file  object to  pikle.load, not a  file name  or path.
