### ISSUE TITLE
sess.run() blocks

### ISSUE THREAD

**Issue by scutzck033** [brightmart/text_classification#2]
Hello! I am new to tensorflow and when I run your model TextCNN, I get a issue, that is, sess.run() blocks. 
I can only get the print before the code: "curr_loss,curr_acc,_=sess.run([textCNN.loss_val,textCNN.accuracy,textCNN.train_op],feed_dict=feed_dict)" and then , the program blocks! I already make sure the input data exists and I fail to figure it out.
Hope you can give me the answer, thanks for your patience.

**Comment by brightmart** [comment]
have you already solved your problem?

**Comment by scutzck033** [comment]
Yes! Thanks for your attention!
It is actually a rookie mistake. sess.run() doesn't block forever, I just have to wait for several minutes and then I can get the following outputs. @brightmart
