### ISSUE TITLE
What is the "zhihu-word2vec-multilabel.bin-100" file?  Can I use "zhihu-word2vec-title-desc.bin-100" instead?

### ISSUE THREAD

**Issue by Vasonv** [brightmart/text_classification#21]

**Comment by brightmart** [comment]
Hi,


 "zhihu-word2vec-multilabel.bin-100"  is a word-embedding file generated  by word2vec using dataset for multi-label dataset.  each line from dataset like "X1 X2 X3 __lable__label1 label2 label2".


"zhihu-word2vec-title-desc.bin-100" is a word-embedding file generated by word2vec using dataset for single-label dataset. each line from dataset like "X1 X2 X3 __lable__label1"


you can do that if you like


Bright

________________________________
发件人: Vasonv <notifications@github.com>
发送时间: 2017年9月27日 11:04
收件人: brightmart/text_classification
抄送: Subscribed
主题: [brightmart/text_classification] What is the "zhihu-word2vec-multilabel.bin-100" file? Can I use "zhihu-word2vec-title-desc.bin-100" instead? (#21)


―
