### ISSUE TITLE
Getting error during running fasttext_train

### ISSUE THREAD

**Issue by behnazeslami** [brightmart/text_classification#24]
@brightmart 
Hi Mr.Brightmart
I want to run fast text, but in first step for running train - during running train I've got below error :
![error-fast text](https://user-images.githubusercontent.com/3388317/33883658-d945010c-df51-11e7-879d-2a317cde88e3.jpg)

Actually I have 2 datasets (one for economic_news and one for lifestyle -- totally there are 14000 documents) in both of them at the end of each document with __label__ labels have been defined.
I attached them 
[train-zhihu4-only-title-all.txt](https://github.com/brightmart/text_classification/files/1551483/train-zhihu4-only-title-all.txt)
Also I made some changes on these 3 program :

[data_util_zhihu.txt](https://github.com/brightmart/text_classification/files/1551517/data_util_zhihu.txt)
[p5_fastTextB_model.txt](https://github.com/brightmart/text_classification/files/1551518/p5_fastTextB_model.txt)
[p5_fastTextB_train.txt](https://github.com/brightmart/text_classification/files/1551519/p5_fastTextB_train.txt)

**Comment by brightmart** [comment]
from your screenshots, we can see that almost every thing for x and y is 0(e.g trainX,trainY). may be there is some error when you preprocess your data.
