### ISSUE TITLE
sample data, pre-trained word embedding

### ISSUE THREAD

**Issue by hpduong** [brightmart/text_classification#3]
I'm getting this issue when I run training on a08 entity network and a06 seq2seq models. 

Can I get or train this file? 

zhihu-word2vec-title-desc.bin-100

![screenshot_20170720_171417](https://user-images.githubusercontent.com/4432141/28444024-e80096d4-6d6e-11e7-85f4-6cafa70753e8.jpg)

Also, do you have sample datasets compatible with these models?

**Comment by brightmart** [comment]
please find it in https://pan.baidu.com/s/1kVgdDD9

**Comment by sersoage** [comment]
Could you please upload it in a different service? I am having a hard time downloading the data and word2vec model. Thanks!

**Comment by yinjianhong** [comment]
brightmart是排行榜上的哪位大神啊？

**Comment by brightmart** [comment]
you can follow two steps to get the file.
step1: click the place for download
![default](https://user-images.githubusercontent.com/19634224/28698777-2e421de8-7378-11e7-80e5-da5521f18ea3.png)

step2: download the file
![step2](https://user-images.githubusercontent.com/19634224/28698752-fecaf6fc-7377-11e7-8fa8-22a545264ebf.JPG)

**Comment by Cauchyzhou** [comment]
When I run TextRNN model. Terminal reports : 
IOError: [Errno 2] No such file or directory: '../zhihu-word2vec.bin-100'
There is no link about zhihu-word2vec.bin-100.

**Comment by brightmart** [comment]
you may use zhihu-word2vec-title-desc.bin-100
.bin file is just a word embedding file trained from word2vec.

**Comment by jacky20172017** [comment]
where is the file:  /test-zhihu-forpredict-title-desc-v6.txt
IOError: [Errno 2] No such file or directory: '../test-zhihu-forpredict-title-desc-v6.txt'

**Comment by jacky20172017** [comment]
and also: train-zhihu6-title-desc.txt

**Comment by jacky20172017** [comment]
when running the p1_HierarchicalAttention_train.py :
ValueError: Parent directory of checkpoint_hier_atten_title/text_hier_atten_title_desc_checkpoint_MHA/model.ckpt doesn't exist, can't save.

so many bugs ... ...

**Comment by jacky20172017** [comment]
when running the a08_predict_ensemble.py: 
argparse.ArgumentError: argument --ckpt_dir_cnn_256_embedding: conflicting option string(s): --ckpt_dir_cnn_256_embedding

so many bugs ... ...

**Comment by jacky20172017** [comment]
there're  2 data_util_zhihu.py  in folders aa1_data_util and a07_Transformer
which one to import?

**Comment by jacky20172017** [comment]
what's the data_type ?

train, test, _ = load_data(vocabulary_word2index, vocabulary_word2index_label,data_type='train')
TypeError: load_data() got an unexpected keyword argument 'data_type'

**Comment by pmahend1** [comment]
I cant see files there in the links mentioned

#########################


    for zhihu-word2vec-title-desc.bin-100, please find it in:
    https://pan.baidu.com/s/1kVgdDD9

    for sample data (multi-label. file name:test-zhihu6-title-desc.txt), you can find it in:
    https://pan.baidu.com/s/1gf49auB

    train-zhihu4-only-title-all.txt (single-label):
    https://pan.baidu.com/s/1jI7R4X4
#########################################

Could you please upload them to https://github.com/brightmart/text_classification in sample data folder?

**Comment by pmahend1** [comment]
Nevermind. After few tries the above links worked!

**Comment by deatherving** [comment]
@pmahend1 Same. The bin100 is not downloading even in China.

**Comment by brightmart** [comment]
@pmahend1  @deatherving 
for zhihu-word2vec-title-desc.bin-100, please use this:
https://pan.baidu.com/s/1jIP9e6q

**Comment by deatherving** [comment]
@brightmart Thanks. The file is accessible.

**Comment by searchlink** [comment]
when I run p5_fastTextB_predict.py ,where come with the error below:
FileNotFoundError: [Errno 2] No such file or directory: 'test-zhihu-forpredict-v4only-title.txt'
In addition,where is zhihu-word2vec-multilabel.bin-100?

**Comment by brightmart** [comment]
Hi,


You can download some test data ,find it from closed issue.


Bright


________________________________
发件人: sky_shine <notifications@github.com>
发送时间: 2017年12月6日 13:57
收件人: brightmart/text_classification
抄送: brightmart; Mention
主题: Re: [brightmart/text_classification] sample data, pre-trained word embedding (#3)


when I run p5_fastTextB_predict.py ,where come with the error below:
FileNotFoundError: [Errno 2] No such file or directory: 'test-zhihu-forpredict-v4only-title.txt'
In addition,where is zhihu-word2vec-multilabel.bin-100?

―

**Comment by pmahend1** [comment]
@brightmart I could download the file now. Thanks 👍

**Comment by behnazeslami** [comment]
@brightmart Hi,
After running p8_TextRNN_train.py 've got this error :

```
File "./p8_TextRNN_train.py", line 117, in main
    test_loss, test_acc = do_eval(sess, textRNN, testX, testY, batch_size,vocabulary_index2word_label)
  File "./p8_TextRNN_train.py", line 167, in do_eval
    return eval_loss/float(eval_counter),eval_acc/float(eval_counter)
ZeroDivisionError: float division by zero
```
I checked do_eval function in train, there is a for that it doesn't work.
I attached them as below :
![111](https://user-images.githubusercontent.com/3388317/33803909-c8638c76-ddaf-11e7-92cb-ae7ae2958f83.jpg)

![222](https://user-images.githubusercontent.com/3388317/33803911-ce14d4a4-ddaf-11e7-8036-ac0d8dcad960.jpg)

**Comment by yjiafei** [comment]
I can't find information about 'test-zhihu-forpredict-v4only-title.txt' from all closed issue, can you provide the url for it @brightmart

**Comment by iqrasafder** [comment]
above links to download "zhihu-word2vec-title-desc.bin-100'  are not working.
please share some working links to download data.
 
Thanks

**Comment by iqrasafder** [comment]
@brightmart please share links to download dataset.

**Comment by arunarn2** [comment]
@brightmart Do I need an account on pan.baidu.com to download the dataset. Can you please upload the data to the repo?

**Comment by brightmart** [comment]
no need account.

**Comment by parahaoer** [comment]
what directory should I put the file ‘zhihu-word2vec-title-desc.bin-100’？
Thanks！

**Comment by liangtianxin** [comment]
thank you so much

**Comment by JaeZheng** [comment]
@parahaoer I think put it in the same directory with the "model_train.py". For example, when you use TextCNN  in the directory"a02_TextCNN",  you process p7_TextCNN_train.py to train the model, at this time you should put the file 'zhihu-word2vec-title-desc.bin-100’ in the same directory.

**Comment by harikrishnanrajeev** [comment]
Could you please upload data 'zhihu-word2vec-title-desc.bin-100’ as well.  The links do not work. Appreciate any quick response.

**Comment by parahaoer** [comment]
@JaeZheng It didn't work

**Comment by kevinsay** [comment]
@brightmart I load the zhihu-word2vec-title-desc.bin-100 as the wordvector file,train-zhihu4-only-title-part1.txt as the trainning file,set multi_label_flag=false,use_embedding=true,
a01_FastText，a03_TextRNN，a04_TextRCNN，a05_HierarchicalAttentionNetwork，a06_Seq2seqWithAttention，these models can run，but the accuracy is very low，i don't know why.
and predict，also set multi_label_flag=false,use_embedding=true,there will be more than one prediction label，i need you help.thanks.

**Comment by brightmart** [comment]
hi. thanks for your feedback. as long as you can see that training and validation loss during training process is decreasing, it will be fine. the previous reported f1 score is not a right indicator of accuracy. I am updating it today.

it is good to see that you can make it work for these several models. can you commit your version to this repository as a new branch?

**Comment by hlshao** [comment]
Respect Sir:

It is a good project!
Could you please provide the file "zhihu-word2vec-title-desc.bin-100" in some where?
and the link below is out of date too... 
Many thanks if you can help.

[NEW, try use this, update 2018-08-12]
zhihu-title-desc-multiple-label-v6.txt.zip, it contains three files:
https://pan.baidu.com/s/1mHgELJUHewQZ9zHDo_uhmA
train-zhihu-title-desc-multiple-label-v6.txt(around 3 million training data, multiple labels)
test-zhihu-title-desc-multiple-label-v6.txt(around 70k validation/test data,multiple labels)
train-zhihu-title-desc-multiple-label-200k-v6.txt( 200k training data,multiple labels, a subset of file one.)

**Comment by peterHeuz** [comment]
I am using the TextRNN (a03) and cannot find this flag. Neither the download are working.

I have changed following in p8_TextRNN_train.py:
`tf.app.flags.DEFINE_boolean("use_embedding", False,
                            "whether to use embedding or not.")`

but the error is still the same:
`IOError: [Errno 2] No such file or directory: 'zhihu-word2vec.bin-100'`

I have also changed this flag in a02_TextCNN since the TextRNN uses code (`data_util_zhihu.py`) from this part. The error is still the same.

Can you please share the pretrained embeddings or point me to the right place?

**Comment by Gunjitbedi** [comment]
Cant down load file 'test-zhihu-forpredict-title-desc-v6.txt', please share it on any other platform

**Comment by brightmart** [comment]
re-generated data, and save as cached file, available to download. check this session in README.md:
 
#Sample data: cached file

**Comment by wuliuyuedetian** [comment]
> where is the file: /test-zhihu-forpredict-title-desc-v6.txt
> when running the a8_predict.py:
> IOError: [Errno 2] No such file or directory: '../test-zhihu-forpredict-title-desc-v6.txt'
Me too

**Comment by Aivi001** [comment]
> I am using the TextRNN (a03) and cannot find this flag. Neither the downloads are working.
> 
> I have changed following in p8_TextRNN_train.py:
> `tf.app.flags.DEFINE_boolean("use_embedding", False, "whether to use embedding or not.")`
> 
> but the error is still the same:
> `IOError: [Errno 2] No such file or directory: 'zhihu-word2vec.bin-100'`
> 
> I have also changed this flag in a02_TextCNN since the TextRNN uses code (`data_util_zhihu.py`) from this part. The error is still the same.
> 
> Can you please share the pretrained embeddings or point me to the right place?
> 
> edit: This one seems to be up to date: https://pan.baidu.com/s/1jIP9e6q. I am using your instructions to download @brightmart . After step 1 I get a windows that tells me to download the netdisk client from Baidu:
> 
> ![screen shot 2018-08-29 at 08 05 16](https://user-images.githubusercontent.com/7074913/44768673-5a9a3380-ab62-11e8-9008-531e52388981.png)
> 
> The installer is in Chinese, which I don't speak, and there is no english version.
> Could anyone who has it please upload with another service? Like google, dropbox, onedrive? @deatherving @liangtianxin and anyone else who has it. Would be appreciated.

Hi, I'm facing the same problem, how did you solve it? Thanks in advance

**Comment by litomvv** [comment]
hi.where is the file: /test-zhihu-forpredict-title-desc-v6.txt
