### ISSUE TITLE
can not find the module named 'p4_zhihu_load_data'

### ISSUE THREAD

**Issue by jiangweiwang** [brightmart/text_classification#33]
hi,
       I can not find the module named 'p4_zhihu_load_data', where is it?thanks.

**Comment by brightmart** [comment]
please check file data_util_zhihu.py<https://github.com/brightmart/text_classification/blob/master/aa1_data_util/data_util_zhihu.py> under folder: aa1_data_util


________________________________
发件人: jiangweiwang <notifications@github.com>
发送时间: 2018年1月30日 16:13
收件人: brightmart/text_classification
抄送: Subscribed
主题: [brightmart/text_classification] can not find the module named 'p4_zhihu_load_data' (#33)


hi,
I can not find the module named 'p4_zhihu_load_data', where is it?thanks.

―
