### ISSUE TITLE
fastText cannot find p4_zhihu_load_data module

### ISSUE THREAD

**Issue by sidneyzhu** [brightmart/text_classification#37]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-7efc1270518e> in <module>()
      8 import numpy as np
      9 from p5_fastTextB_model import fastTextB as fastText
---> 10 from p4_zhihu_load_data import load_data,create_voabulary,create_voabulary_label
     11 from tflearn.data_utils import to_categorical, pad_sequences
     12 import os

ModuleNotFoundError: No module named 'p4_zhihu_load_data'

**Comment by brightmart** [comment]
check aa1_data_util/data_util_zhihu.py

**Comment by brightmart** [comment]
UPDATE: if you want to try a model now, you can go to folder 'a02_TextCNN', run 'python -u p7_TextCNN_train.py', it will use sample data to train a model, and print loss and F1 score periodically.
