### ISSUE TITLE
Errors when debugging

### ISSUE THREAD

**Issue by wyl6** [brightmart/text_classification#42]
As a noob,I find it hard to debug your programs.There are too many problems...
Dear author,would you please provide even one complete code that could run directly?

Besides,I would really appreciate it if you explain how to make personal files similar with 'zhihu-word2vec-title-desc.bin-100'.

**Comment by liangtianxin** [comment]
zhihu-word2vec-title-desc.bin-100'.  I  have the same qusetion? how can i get  the file "zhihu-word2vec-title-desc.bin-100'"

**Comment by brightmart** [comment]
yeah. for 'zhihu-word2vec-title-desc.bin-100', you can use data to pre-trained word embedding. for example, use word2vec or fasttext to pre-trained it. then you will get it.

**Comment by brightmart** [comment]
UPDATE: if you want to try a model now, you can go to folder 'a02_TextCNN', run 'python -u p7_TextCNN_train.py', it will use sample data to train a model, and print loss and F1 score periodically.

**Comment by wyl6** [comment]
thank you so much!

在 2018-04-16 22:19:11，brightmart <notifications@github.com> 写道：


UPDATE: if you want to try a model now, you can go to folder 'a02_TextCNN', run 'python -u p7_TextCNN_train.py', it will use sample data to train a model, and print loss and F1 score periodically.
