### ISSUE TITLE
does not support multi-label classification

### ISSUE THREAD

**Issue by acadTags** [brightmart/text_classification#43]
Thank you for sharing these wonderful codes!

Just one issue, it seems in a03 TextRNN, the result part (self.predictions) does not support multi-label classification. There is a lot to change if I want to adapt it to a multi-label classification task. Also the inference part is mostly about single label classification.

Best wishes,
Hang

**Comment by brightmart** [comment]
Hi. you may refer to model under folder: a02_TextCNN/ to find better support of multi-label classification
