### ISSUE TITLE
ImportError: No module named p4_zhihu_load_data

### ISSUE THREAD

**Issue by parahaoer** [brightmart/text_classification#44]
当我运行 p5_fastTextB_train.py时，报错ImportError: No module named p4_zhihu_load_data
该怎么办呢？

**Comment by brightmart** [comment]
hi. you run check a02_TextCNN/xxx_train.py first. it can work. and you will some functions for preprocess data.

**Comment by parahaoer** [comment]
thanks very much！

**Comment by Delysky** [comment]
good good
