### ISSUE TITLE
ModuleNotFoundError: No module named 'a02_TextCNN'

### ISSUE THREAD

**Issue by nikmodo** [brightmart/text_classification#46]
Issue when trying to run the p7_TextCNN_predict.py after training

ModuleNotFoundError: No module named 'a02_TextCNN'

Question: can you get it running with clean anaconda and Python 3.6 and additional such word2vec, etc. installs ? I think that there are a some code changes needed in the files.

**Comment by brightmart** [comment]
you can change a02_TextCNN to the name of model/file you used.
