### ISSUE TITLE
There is no file named "test-zhihu-forpredict-title-desc-v6.txt" in the Hierarchical Attention Network

### ISSUE THREAD

**Issue by havefun007** [brightmart/text_classification#49]
There is no file named "test-zhihu-forpredict-title-desc-v6.txt",when i run the p1_HierarchicalAttention_predict.py in the Hierarchical Attention Network. Also i have tried to use the test-zhihu6-title-desc.txt instead, but there will be an error. Can you give me some advice? @brightmart

**Comment by brightmart** [comment]
you can try to run TextCNN first. then try HAN by change something
________________________________
发件人: J. Fan <notifications@github.com>
发送时间: 2018年4月29日 21:34:38
收件人: brightmart/text_classification
抄送: brightmart; Mention
主题: [brightmart/text_classification] There is no file named "test-zhihu-forpredict-title-desc-v6.txt" in the Hierarchical Attention Network (#49)


There is no file named "test-zhihu-forpredict-title-desc-v6.txt",when i run the p1_HierarchicalAttention_predict.py in the Hierarchical Attention Network. Also i have tried to use the test-zhihu6-title-desc.tex instead, but there will be a error @brightmart<https://github.com/brightmart>

―
