### ISSUE TITLE
Flake8: F821 undefined name 'predict'

### ISSUE THREAD

**Issue by cclauss** [brightmart/text_classification#5]
flake8 testing of https://github.com/brightmart/text_classification on Python 2.7.13

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./a07_Transformer/a2_predict.py:102:55: F821 undefined name 'predict'
            print("===============>",start,"predict:",predict)
                                                      ^
```

**Comment by brightmart** [comment]
this line is just to print some message. removed.
