### ISSUE TITLE
请问p71_TextRCNN_model.py中rnn-cnn layer定义原理是什么？最后ensemble left, embedding, right to output的方式不像Bi-LSTM layer呀

### ISSUE THREAD

**Issue by JepsonWong** [brightmart/text_classification#51]

**Comment by brightmart** [comment]
this is just like taking context information(from left and right) into considering when encode a position to get rich information.


________________________________
发件人: JepsonWong <notifications@github.com>
发送时间: 2018年5月8日 10:35
收件人: brightmart/text_classification
抄送: Subscribed
主题: [brightmart/text_classification] 请问p71_TextRCNN_model.py中rnn-cnn layer定义原理是什么？最后ensemble left, embedding, right to output的方式不像Bi-LSTM layer呀 (#51)


―

**Comment by fei161** [comment]
The meaning of the paper should be two layers of lstm followed by cnn layer features, why is there no lstm and cnn in your code?

**Comment by fei161** [comment]
@brightmart  thank you !

**Comment by JepsonWong** [comment]
When you get context right, you reverse the input sequences, but you don't reverse the output sequences. I think the output seqences should be reversed.
By the way, do you implement a rnn cell by yourself in your source code? So you don't use the tensorflow's api.
thanks.@brightmart

**Comment by JepsonWong** [comment]
I guess the author implement a rnn cell in his source code.
https://github.com/brightmart/text_classification/blob/a552e115a54b3d3f0736d418bd1b41a30550815b/a04_TextRCNN/p71_TextRCNN_model.py#L51
this is the rnn weights.
@fei161

**Comment by fei161** [comment]
The author first makes a full connection to the context. Then concatenates the context vector concat and maximizes it. Finally connects to the full connection layer.
@JepsonWong

**Comment by JepsonWong** [comment]
yes, i know this. I just think that when we get context right, we should reverse the output sequences.
@fei161
