### ISSUE TITLE
Is it possible to implement Hierarchical Attention Network with parsing real sentences?

### ISSUE THREAD

**Issue by acadTags** [brightmart/text_classification#58]
Thank you a lot for your sharing.

I find that in your implementation of Hierarchical Attention Network (HAN), the sentences are separated through setting an equal sentence length. This is however not the true sentence length in the data. 

I wonder if it is easy to change this to using a sentence parser to find the sentences? How would be the difference in performance?

Please kindly let me know if you have any idea on parsing the real sentences based on your HAN code. Many thanks!

**Comment by brightmart** [comment]
Hi,


Good to hear from you.


I think it is a good to send real sentence to the HAN network.


for example, if total length of a document is 400. now it is split as 10 sentences, each with 40 words.


so you can prepare 10 sentence spaces, the max length of each sentence is 40.


any word exceed of 40 will be truncated, pad where necessary.


by doing so in data processing step, you can send real sentence to the network,


I think it may improve performance.


Bright

________________________________
发件人: acadTags <notifications@github.com>
发送时间: 2018年5月31日 15:51
收件人: brightmart/text_classification
抄送: Subscribed
主题: [brightmart/text_classification] Is it possible to implement Hierarchical Attention Network with parsing real sentences? (#58)


Thank you a lot for your sharing.

I find that in your implementation of Hierarchical Attention Network (HAN), the sentences are separated through setting an equal sentence length. This is however not the true sentence length in the data.

I wonder if it is easy to change this to using a sentence parser to find the sentences? How would be the difference in performance?

Please kindly let me know if you have any idea of how to implement parsing the real sentences based on your HAN code. Many thanks!

―

**Comment by acadTags** [comment]
Hi Bright, 

Thank you. I find using real sentences sometimes can boost the results by about 1%, but sometimes even slightly lower than using fake sentences. Anyway, very little difference is found.
