### ISSUE TITLE
text rcnn 模型，反向拼接[left_context,embedded,right_context]，right_context有错误

### ISSUE THREAD

**Issue by PeterMao11** [brightmart/text_classification#60]
您的代码在处理反向的上下文后，未对context_right_list进行反转处理，那么新的输入则会拼接为[cl0,x1,cr0],其中cr0是xn的反向上文。实际论文中需要的是x1的反向上文。

**Comment by brightmart** [comment]
thank you for your comment. yeah, we can do that.
