### ISSUE TITLE
About Free Usage License

### ISSUE THREAD

**Issue by bikramkhastgir** [brightmart/text_classification#61]
HI brightmart,
Further to issue #52 

Can you please a "The MIT License" to it. It is difficult to use this source as open source while building an application or presenting in competitions. Without a 'MIT' license this code is not reusable in parts or in whole in other open source projects.

**Comment by bikramkhastgir** [comment]
I have initiated a pull request with the License file.

**Comment by brightmart** [comment]
fine. i will try to accept it
________________________________
发件人: IronMelter <notifications@github.com>
发送时间: 2018年6月20日 14:01:32
收件人: brightmart/text_classification
抄送: Subscribed
主题: Re: [brightmart/text_classification] About Free Usage License (#61)


I have initiated a pull request with the License file.

―

**Comment by bikramkhastgir** [comment]
Thank you... I will wait for it.. :)

**Comment by brightmart** [comment]
I've just merge the license file. @bikramkhastgir
