### ISSUE TITLE
能提供a02_TextCNN完整的数据吗？

### ISSUE THREAD

**Issue by kevinsay** [brightmart/text_classification#67]
create_voabulary_label_sorted.ended.len of vocabulary_label: 1999
Traceback (most recent call last):
  File "p7_TextCNN_predict.py", line 42, in <module>
    questionid_question_lists = load_final_test_data(FLAGS.predict_source_file)
  File "/home/text_classification-master/a02_TextCNN/other_experiement/data_util_zhihu.py", line 411, in load_final_test_data
    final_test_file_predict_object = codecs.open(file_path, 'r', 'utf8')
  File "/usr/lib/python3.5/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'test-zhihu-forpredict-title-desc-v6.txt'

**Comment by brightmart** [comment]
which data set you are using? if you use default dataset, it has 1999 tables, with few sample data.
you can use your own data,\.
________________________________
发件人: RuanJingqing <notifications@github.com>
发送时间: 2018年10月25日 9:24
收件人: brightmart/text_classification
抄送: Subscribed
主题: Re: [brightmart/text_classification] 能提供a02_TextCNN完整的数据吗？ (#67)


为什么单标签的准确率只有百分之20左右 啊，，，怎么这么低啊

―

**Comment by brightmart** [comment]
re-generated data, and save as cached file, available to download. check this session in README.md:
 #Sample data: cached file
