### ISSUE TITLE
Questions about hierarchical attention network 

### ISSUE THREAD

**Issue by yangdelu855** [brightmart/text_classification#72]
In your previous test function, given 10 samples with same content(all zeros) but different labels in a batch, we train the model for several times, the acc can arrive 100%. I just wonder, how the model tells the docs with all zeros from each other, and predict different labels for them?Is there anything wrong?
![ca14c201-2aca-45be-9db8-dcb7ac95b022](https://user-images.githubusercontent.com/34619524/42922941-a080371e-8b55-11e8-8522-0538e253bd21.png)
![b2f59929-5885-4b8f-9d0f-3878553b87ed](https://user-images.githubusercontent.com/34619524/42922973-c2e67e8a-8b55-11e8-8983-2a7afa9ef774.png)

**Comment by brightmart** [comment]
hi. for the same input(x), the label(y) should be same. so you've better come up a new toy task if you like.
