### ISSUE TITLE
a01_FastText

### ISSUE THREAD

**Issue by chenting0324** [brightmart/text_classification#73]
Hi,
In data_util_zhihu.py:
def create_voabulary(simple=None,word2vec_model_path='zhihu-word2vec-title-desc.bin-100',name_scope='')
but your data is zhihu-word2vec-title-desc.bin-100.txt, should I add the .txt to the path, but if I do this, it will have other errors

**Comment by eureka2012** [comment]
rename the txt file: zhihu-word2vec-title-desc.bin-100
