### ISSUE TITLE
model accuracy is very low,i don't know why?

### ISSUE THREAD

**Issue by kevinsay** [brightmart/text_classification#74]
I load the zhihu-word2vec-title-desc.bin-100 as the wordvector file,train-zhihu4-only-title-all.txt as the trainning file,set multi_label_flag=false,use_embedding=true,
a01_FastText
a03_TextRNN
a04_TextRCNN
a05_HierarchicalAttentionNetwork
a06_Seq2seqWithAttention
these models can run,but the accuracy is very low,i don't know why.
and predict,also set multi_label_flag=false,use_embedding=true,there will be more than one prediction label,i need you help.thanks.

**Comment by f20500909** [comment]
may i ask you where did you find **zhihu-word2vec-title-desc.bin-100** file.
I can find it in the project , did you generate it ?

**Comment by kevinsay** [comment]
i get it from author Baidu cloud  sharing,we can also use google word2vec to generate it.

**Comment by f20500909** [comment]
I use **create_voabulary** funtion to generate vocab_label.pik to substitute zhihu-word2vec-title-desc.bin-100 file.
But I can not find the Baidu cloud sharing link in **README.m**d,i think it is very helpful for us to study this project.
I would be very grateful if you could share it, can you have a share?
@kevinsay

**Comment by kevinsay** [comment]
link：https://pan.baidu.com/s/1orPKC0cahrIW0CUvPxts1g 
pwd：bguc
i share the file to you，and hope you can share your trainning and predict results with me.

**Comment by f20500909** [comment]
Thank you very much.
After I comprehend the code and run it accurately. i will share my corpus and trainning and predict results with  you
It's very greatful of you to share these files    
@kevinsay

**Comment by lreaderl** [comment]
@kevinsay I meet some problem while training on single label classification on textCNN, may I ask you about your modification?
My modification: set multi_label_flag=false,use_embedding=true, and thus a problem occur

> ValueError: Cannot feed value of shape (64, 19) for Tensor 'input_y:0', which has shape '(?,)'

The input_y is defined in model.py, it has different shape compare to trainY[start:end] in feed_dict in train.py. Have you ever met the problem?

**Comment by lreaderl** [comment]
Hello, my F1 score is very low on single label classification as below:
`Epoch 19 Validation Loss:2.709	F1 Score:0.282	Precision:0.169	Recall:0.846`
Have you find any solution to that?

**Comment by brightmart** [comment]
hi, which kinds of data and trining size you use?


________________________________
发件人: lreaderl <notifications@github.com>
发送时间: 2018年8月6日 0:11
收件人: brightmart/text_classification
抄送: Subscribed
主题: Re: [brightmart/text_classification] model accuracy is very low,i don't know why? (#74)


Hello, my F1 score is very low on single label classification as below:
Epoch 19 Validation Loss:2.709 F1 Score:0.282 Precision:0.169 Recall:0.846
Have you find any solution to that?

―

**Comment by lreaderl** [comment]
My dataset has 19 classes, with about 100000 training samples. And the average length of training data is about 150.

**Comment by kevinsay** [comment]
@f20500909 ok，thanks.

**Comment by kevinsay** [comment]
@brightmart Does the length of training sample affect the accuracy of the model?one of my datasets，the average length of the sample is 10,but i pad_sequences them to 20,50 or 100 when i train model，accuracy is low.

**Comment by brightmart** [comment]
if implement correctly, pad should have mini impact to performance, as you can mask out the embedding  from pad token.
