### ISSUE TITLE
a08_EntityNetwork

### ISSUE THREAD

**Issue by Alicebupt** [brightmart/text_classification#75]
您好，EntityNetwork中，当multi_label_flag为True时，trainY和testY的格式应该是什么样？？训练单个label的时候是一个list，每一项是一个数字，训练多个label时不是很清楚

**Comment by brightmart** [comment]
for multiple label:
"c324 c889 c153 c12 c431 c11 c1295 c1410 c775 c783 c44 c835 c57 c27 c74 c184 __label__4697494136307113064 __label__3833854281930673428 __label__6170121829697589402"
