### ISSUE TITLE
fasttext loss and the long text classification

### ISSUE THREAD

**Issue by songzenghui** [brightmart/text_classification#78]
NICE project!
I have two issues,could u or someone else give me some idea?
+  Why the fasttext 's loss is different between training and eval?
+ How to deal with the long text classification ,which its max length maybe 40,000 min length maybe 10,but its most length is 500-600
Thank you

**Comment by brightmart** [comment]
hi,


basically,  use a special loss for training to speed up the training process.

for long text classification, you can check models under:

https://github.com/brightmart/ai_law, which is handling documents, and the average length is around 400.

GitHub - brightmart/ai_law: all kinds of baseline models ...<https://github.com/brightmart/ai_law>
github.com
Update: Joint Model for law cases prediction is released. run python HAN_train.py to train the model for predict accusation, relevant articles and term of imprisonment. challenges of this task: the description of law case(called facts) is quite long, the average words is around 400. it is not only ...




________________________________
发件人: Zee <notifications@github.com>
发送时间: 2018年8月11日 21:36
收件人: brightmart/text_classification
抄送: Subscribed
主题: [brightmart/text_classification] fasttext loss and the long text classification (#78)


NICE project!
I have two issues,could u or someone else give me some idea?

  *   Why the fasttext 's loss is different between training and eval?
  *   How to deal with the long text classification ,which its max length maybe 40,000 min length maybe 10

Thank you

―
