### ISSUE TITLE
unable to train the TextCNN model with sample_single_label.txt

### ISSUE THREAD

**Issue by JinChengneng** [brightmart/text_classification#80]
I want to train the TextCNN with single label data, and I have changed `traning_data_path` to `../data/sample_single_label.txt` and `multi_label_flag` to `False`. 
However it doesn't work. 
The error info is `AttributeError: 'TextCNN' object has no attribute 'input_y'`.

**Comment by brightmart** [comment]
it is ok to keep flag of multiple label as true when train single label
________________________________
发件人: Jin Chengneng <notifications@github.com>
发送时间: 2018年8月17日 14:50:49
收件人: brightmart/text_classification
抄送: Subscribed
主题: [brightmart/text_classification] unable to train the TextCNN model with sample_single_label.txt (#80)


I want to train the TextCNN with single label data, and I have changed traning_data_path to ../data/sample_single_label.txt and multi_label_flag to False.
However it doesn't work.
The error info is AttributeError: 'TextCNN' object has no attribute 'input_y'.

―

**Comment by Amanda-1997** [comment]
I have tried to keep flag of multiple label  as true  and change the path to ../data/sample_single_label.txt   when train single label,but it doesn't work, how should I do?

**Comment by brightmart** [comment]
by download cached file, you will able to train TextCNN. for more detail check this session #Sample data: cached file
